// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmbzxaikjtvscnwzxvso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYnp4YWlranR2c2Nud3p4dnNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMDgxMjEsImV4cCI6MjA2MjU4NDEyMX0.k8iEAKZO5SSxNgph4IzYaX2kbT73KKxMjAJNwdKYIt4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);